services:
  client:
    build:
      context: ..
      target: production-stage
      args:
        NEXT_PUBLIC_SUPABASE_URL: http://${HOST_IP}:${KONG_HTTP_PORT:-8000}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${ANON_KEY}
        NEXT_PUBLIC_APP_PLATFORM: web
        NEXT_PUBLIC_API_BASE_URL: http://${HOST_IP}:3000
        NEXT_PUBLIC_OBJECT_STORAGE_TYPE: s3
        NEXT_PUBLIC_STORAGE_FIXED_QUOTA: ${STORAGE_FIXED_QUOTA}
        NEXT_PUBLIC_TRANSLATION_FIXED_QUOTA: ${TRANSLATION_FIXED_QUOTA}
